package com.ednerdaza.activitytechnology.testapplicationbinary.mvc.models.entities;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "CLIENTES_ENTITY".
 */
@Entity
public class ClientesEntity {

    @Id
    private Long id;
    private Integer Cedula;
    private String Nombre;
    private String Telefono;
    private String Email;

    @Generated
    public ClientesEntity() {
    }

    public ClientesEntity(Long id) {
        this.id = id;
    }

    @Generated
    public ClientesEntity(Long id, Integer Cedula, String Nombre, String Telefono, String Email) {
        this.id = id;
        this.Cedula = Cedula;
        this.Nombre = Nombre;
        this.Telefono = Telefono;
        this.Email = Email;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getCedula() {
        return Cedula;
    }

    public void setCedula(Integer Cedula) {
        this.Cedula = Cedula;
    }

    public String getNombre() {
        return Nombre;
    }

    public void setNombre(String Nombre) {
        this.Nombre = Nombre;
    }

    public String getTelefono() {
        return Telefono;
    }

    public void setTelefono(String Telefono) {
        this.Telefono = Telefono;
    }

    public String getEmail() {
        return Email;
    }

    public void setEmail(String Email) {
        this.Email = Email;
    }

}
