package com.ednerdaza.activitytechnology.testapplicationbinary.mvc.models.entities;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "USUARIOS_ENTITY".
 */
@Entity
public class UsuariosEntity {

    @Id
    private Long id;
    private String Nombre;
    private String Contrasena;
    private Integer NivelPermiso;

    @Generated
    public UsuariosEntity() {
    }

    public UsuariosEntity(Long id) {
        this.id = id;
    }

    @Generated
    public UsuariosEntity(Long id, String Nombre, String Contrasena, Integer NivelPermiso) {
        this.id = id;
        this.Nombre = Nombre;
        this.Contrasena = Contrasena;
        this.NivelPermiso = NivelPermiso;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNombre() {
        return Nombre;
    }

    public void setNombre(String Nombre) {
        this.Nombre = Nombre;
    }

    public String getContrasena() {
        return Contrasena;
    }

    public void setContrasena(String Contrasena) {
        this.Contrasena = Contrasena;
    }

    public Integer getNivelPermiso() {
        return NivelPermiso;
    }

    public void setNivelPermiso(Integer NivelPermiso) {
        this.NivelPermiso = NivelPermiso;
    }

}
