package com.ednerdaza.activitytechnology.testapplicationbinary.mvc.models.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.ednerdaza.activitytechnology.testapplicationbinary.mvc.models.entities.PermisosEntity;
import com.ednerdaza.activitytechnology.testapplicationbinary.mvc.models.entities.UsuariosEntity;
import com.ednerdaza.activitytechnology.testapplicationbinary.mvc.models.entities.ClientesEntity;

import com.ednerdaza.activitytechnology.testapplicationbinary.mvc.models.dao.PermisosEntityDao;
import com.ednerdaza.activitytechnology.testapplicationbinary.mvc.models.dao.UsuariosEntityDao;
import com.ednerdaza.activitytechnology.testapplicationbinary.mvc.models.dao.ClientesEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig permisosEntityDaoConfig;
    private final DaoConfig usuariosEntityDaoConfig;
    private final DaoConfig clientesEntityDaoConfig;

    private final PermisosEntityDao permisosEntityDao;
    private final UsuariosEntityDao usuariosEntityDao;
    private final ClientesEntityDao clientesEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        permisosEntityDaoConfig = daoConfigMap.get(PermisosEntityDao.class).clone();
        permisosEntityDaoConfig.initIdentityScope(type);

        usuariosEntityDaoConfig = daoConfigMap.get(UsuariosEntityDao.class).clone();
        usuariosEntityDaoConfig.initIdentityScope(type);

        clientesEntityDaoConfig = daoConfigMap.get(ClientesEntityDao.class).clone();
        clientesEntityDaoConfig.initIdentityScope(type);

        permisosEntityDao = new PermisosEntityDao(permisosEntityDaoConfig, this);
        usuariosEntityDao = new UsuariosEntityDao(usuariosEntityDaoConfig, this);
        clientesEntityDao = new ClientesEntityDao(clientesEntityDaoConfig, this);

        registerDao(PermisosEntity.class, permisosEntityDao);
        registerDao(UsuariosEntity.class, usuariosEntityDao);
        registerDao(ClientesEntity.class, clientesEntityDao);
    }
    
    public void clear() {
        permisosEntityDaoConfig.clearIdentityScope();
        usuariosEntityDaoConfig.clearIdentityScope();
        clientesEntityDaoConfig.clearIdentityScope();
    }

    public PermisosEntityDao getPermisosEntityDao() {
        return permisosEntityDao;
    }

    public UsuariosEntityDao getUsuariosEntityDao() {
        return usuariosEntityDao;
    }

    public ClientesEntityDao getClientesEntityDao() {
        return clientesEntityDao;
    }

}
